/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { metadata as chatgptai__metadata_ts } from "./chatgptai/_metadata";
import { metadata as facebooksocial__metadata_ts } from "./facebooksocial/_metadata";
import { metadata as googlecloudstorage__metadata_ts } from "./googlecloudstorage/_metadata";
import { metadata as instagramsocial__metadata_ts } from "./instagramsocial/_metadata";
import { metadata as linkedinsocial__metadata_ts } from "./linkedinsocial/_metadata";
import { metadata as threadssocial__metadata_ts } from "./threadssocial/_metadata";
import typeform_config_json from "./typeform/config.json";
import { metadata as xconsumerkeyssocial__metadata_ts } from "./xconsumerkeyssocial/_metadata";

export const appStoreMetadata = {
  chatgptai: chatgptai__metadata_ts,
  facebooksocial: facebooksocial__metadata_ts,
  googlecloudstorage: googlecloudstorage__metadata_ts,
  instagramsocial: instagramsocial__metadata_ts,
  linkedinsocial: linkedinsocial__metadata_ts,
  threadssocial: threadssocial__metadata_ts,
  typeform: typeform_config_json,
  xconsumerkeyssocial: xconsumerkeyssocial__metadata_ts,
};
