/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const apiHandlers = {
  chatgptai: import("./chatgptai/api"),
  facebooksocial: import("./facebooksocial/api"),
  googlecloudstorage: import("./googlecloudstorage/api"),
  instagramsocial: import("./instagramsocial/api"),
  linkedinsocial: import("./linkedinsocial/api"),
  stripepayment: import("./stripepayment/api"),
  threadssocial: import("./threadssocial/api"),
  typeform: import("./typeform/api"),
  xconsumerkeyssocial: import("./xconsumerkeyssocial/api"),
};
