/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { appKeysSchema as facebooksocial_zod_ts } from "./facebooksocial/zod";
import { appKeysSchema as googlecloudstorage_zod_ts } from "./googlecloudstorage/zod";
import { appKeysSchema as instagramsocial_zod_ts } from "./instagramsocial/zod";
import { appKeysSchema as linkedinsocial_zod_ts } from "./linkedinsocial/zod";
import { appKeysSchema as threadssocial_zod_ts } from "./threadssocial/zod";

export const appKeysSchemas = {
  facebooksocial: facebooksocial_zod_ts,
  googlecloudstorage: googlecloudstorage_zod_ts,
  instagramsocial: instagramsocial_zod_ts,
  linkedinsocial: linkedinsocial_zod_ts,
  threadssocial: threadssocial_zod_ts,
};
