/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/

/**
 * Comment/Reply Function Registry
 *
 * Centralized registry for social media platform comment/reply functions.
 * This file is auto-generated. To add a new platform:
 * 1. Create a reply/comment function with signature: (credentialId: number, parentId: string, content: string) => Promise<{success: boolean}>
 * 2. Run `yarn app-store:build` to regenerate this file
 */
import { replyToTweet as xconsumerkeyssocial_replyToTweet } from "./xconsumerkeyssocial/lib";

/**
 * Type definition for a comment handler function
 */
export type CommentHandler = (
  credentialId: number,
  parentId: string,
  content: string
) => Promise<{ success: boolean; [key: string]: any }>;

/**
 * Registry mapping app IDs to their comment handler functions
 */
export const COMMENT_HANDLERS: Record<string, CommentHandler> = {
  "xconsumerkeys-social": xconsumerkeyssocial_replyToTweet,
};

export function getCommentHandler(appId: string): CommentHandler | undefined {
  return COMMENT_HANDLERS[appId];
}

export function hasCommentHandler(appId: string): boolean {
  return appId in COMMENT_HANDLERS;
}

export function getSupportedCommentApps(): string[] {
  return Object.keys(COMMENT_HANDLERS);
}

export async function executeComment(
  appId: string,
  credentialId: number,
  parentId: string,
  content: string
): Promise<{ success: boolean; [key: string]: any }> {
  const handler = getCommentHandler(appId);
  if (!handler) {
    throw new Error(
      `Comment not supported for app: ${appId}. Supported apps: ${getSupportedCommentApps().join(", ")}`
    );
  }
  return handler(credentialId, parentId, content);
}

export const PLATFORMS_WITHOUT_COMMENT_SUPPORT: readonly string[] = ["instagram-social"];
