/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/

/**
 * Post Function Registry
 *
 * Centralized registry for social media platform post functions.
 * This file is auto-generated. To add a new platform:
 * 1. Create a Manager file with `export const post = async (postId: number) => {...}`
 * 2. Run `yarn app-store:build` to regenerate this file
 */
import { post as instagramsocial_Manager_post } from "./instagramsocial/lib";

/**
 * Type definition for a post handler function
 */
export type PostHandler = (postId: number) => Promise<any>;

/**
 * Registry mapping app IDs to their post handler functions
 */
export const POST_HANDLERS: Record<string, PostHandler> = {
  "instagram-social": instagramsocial_Manager_post,
};

export function getPostHandler(appId: string): PostHandler | undefined {
  return POST_HANDLERS[appId];
}

export function hasPostHandler(appId: string): boolean {
  return appId in POST_HANDLERS;
}

export function getSupportedPostApps(): string[] {
  return Object.keys(POST_HANDLERS);
}

export async function executePost(appId: string, postId: number): Promise<any> {
  const handler = getPostHandler(appId);
  if (!handler) {
    throw new Error(`Unsupported app: ${appId}. Supported apps: ${getSupportedPostApps().join(", ")}`);
  }
  return handler(postId);
}
